# Generated by Django 4.0.6 on 2022-08-02 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=40, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id_fabricante', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_fabricante', models.CharField(max_length=40, verbose_name='Nombre fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaCatalogo',
            fields=[
                ('id_familiacat', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_familiacat', models.CharField(max_length=40, verbose_name='Nombre familia')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nit_proveedor', models.CharField(max_length=50, unique=True, verbose_name='Nit')),
                ('nombre_proveedor', models.CharField(max_length=40, verbose_name='Nombre proveedor')),
                ('telefono_proveedor', models.CharField(max_length=40, verbose_name='Telefono proveedor')),
                ('correo_proveedor', models.CharField(max_length=40, unique=True, verbose_name='Correo proveedor')),
                ('direccion_proveedor', models.CharField(max_length=60, verbose_name='Direccion proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=40, verbose_name='Nombre producto')),
                ('marca_producto', models.CharField(max_length=40, verbose_name='Marca producto')),
                ('precio_unit_producto', models.IntegerField(verbose_name='Precio producto')),
                ('resumen_producto', models.CharField(max_length=40, verbose_name='Resumen producto')),
                ('detalle_producto', models.CharField(max_length=255, verbose_name='Dertalle producto')),
                ('categoria_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='coomaterialesApp.categoria')),
                ('fabricante_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricante', to='coomaterialesApp.fabricante')),
                ('proveedor_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor', to='coomaterialesApp.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='familiacat_categoriaFk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familia', to='coomaterialesApp.familiacatalogo'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('nombre_usuario', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido_usuario', models.CharField(max_length=40, verbose_name='Apellido')),
                ('telefono_usuario', models.CharField(max_length=40, verbose_name='Telefono')),
                ('correo_usuario', models.EmailField(max_length=40, unique=True, verbose_name='Correo')),
                ('direccion_usuario', models.CharField(max_length=60, verbose_name='Direccion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol_usuarioFk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Rol', to='coomaterialesApp.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
