# Generated by Django 4.0.6 on 2022-08-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coomaterialesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coomaterialesApp.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante_producto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coomaterialesApp.proveedor'),
        ),
    ]
