# Generated by Django 4.0.6 on 2022-08-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coomaterialesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido_usuario',
            field=models.CharField(max_length=40, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='user',
            name='correo_usuario',
            field=models.EmailField(max_length=256, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion_usuario',
            field=models.CharField(max_length=60, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre_usuario',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono_usuario',
            field=models.CharField(max_length=40, verbose_name='Phone'),
        ),
    ]
