# Generated by Django 4.0.6 on 2022-08-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coomaterialesApp', '0002_alter_producto_categoria_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fabricante_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coomaterialesApp.fabricante'),
        ),
    ]
