# Generated by Django 4.0.6 on 2022-08-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coomaterialesApp', '0002_alter_user_id_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellido_usuario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='correo_usuario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='direccion_usuario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono_usuario',
        ),
    ]
