from .categoriaserializer import CategoriaSerializer
from .fabricanteserializer import FabricanteSerializer
from .productoserializer import ProductoSerializer
from .proveedorserializer import ProveedorSerializer
from .userserializer import UserSerializer